#!/bin/sh

SERVER=localhost
PORT=5003
SEED=1234
TOTAL=1
START=1
DIFFICULTY=1
REP_PROB_PERCENT=0
DELAY_US=100000
PRIO_LAMBDA=0

./bin/client $SERVER $PORT $SEED $TOTAL $START $DIFFICULTY $REP_PROB_PERCENT $DELAY_US $PRIO_LAMBDA
